DROP DATABASE IF EXISTS Lab2;
CREATE DATABASE Lab2;
USE Lab2;

CREATE TABLE Assunto (
    idAssunto INT PRIMARY KEY AUTO_INCREMENT,
    descricao VARCHAR(45) NOT NULL;
);

CREATE TABLE Senha (
    idSenha INT PRIMARY KEY AUTO_INCREMENT,
    dataHoraGerada DATETIME NOT NULL,
    inicioAtendimento DATETIME NOT NULL,
    fimAtendimento DATETIME NOT NULL,
    numeroSenha INT NOT NULL;
);